{{- if .Values.api.enabled }}
{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "corpus.fullname" . }}-api
  labels:
    {{- include "corpus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "corpus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- end }}
---
{{- if .Values.frontend.enabled }}
{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "corpus.fullname" . }}-frontend
  labels:
    {{- include "corpus.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "corpus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- end }}
